# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcf37f665a0b12567e9600f4622a3bdc8ae0f006cf551a058a3ac8f2e2b44b7a70a7a3be40223ce53c6a384571a460563f5a31f50ae5a1c5c366ad235cf57a2a

test:
  secret_key_base: f7019113ff01f6c0de7f3d848142f3cb5e5c8d0dc71822b5078789af7819ec9b2d8cc7a4e927db4711bba785a9705e7d209b2d93dce20900278821405a436c71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
